config/routes.rb
Rails.application.routes.draw do
  get 'friends/index'

  root 'home#top'

  get 'posts/index'
  get 'posts/new'
  post 'posts/create'
  get 'posts/search'
  get 'posts/:id' => 'posts#show'
  get 'posts/:id/edit' => 'posts#edit'
  post 'posts/:id/update' => 'posts#update'
  post 'posts/:id/destroy' => 'posts#destroy'

  get 'request/create'
  get 'request/index'
  get 'request/:id/accept' => 'request#accept'
  get 'request/:id/reject' => 'request#reject'
  get 'request/:id/form' => 'request#form'
  post 'request/:id/create' => 'request#create'

  get 'users/:id/show' => 'users#show'
  get 'users/index'


  get 'notification/:id' => 'notification#show'

  get 'message/:id' => 'message#show' #id = room_id
  post 'message/:id/create' => 'message#create'

  get 'friends/:id' => 'friends#index'

  devise_for :users, :controllers => {
    :registrations => 'users/registrations',
    :sessions => 'users/sessions'
  }

  devise_scope :user do
    get "sign_in", :to => "users/sessions#new"
    get "sign_out", :to => "users/sessions#destroy"
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/friend.rb
class Friend < ApplicationRecord
  belongs_to :user, class_name: 'User', foreign_key: :from_user_id

  validates :from_user_id, :to_user_id, presence: true
  #def friends(id)
  #  f = Friend.where(from_user_id: id)
  #end
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user, class_name: 'User', foreign_key: :from_user_id

  default_scope -> {order(created_at: :asc)}

  # Validations
  validates :from_user_id, presence: true
  validates :to_user_id, presence: true
  validates :room_id, presence: true
  validates :content, presence: true, length: {maximum: 100}

  # Methods
  def Message.recent_in_room(room_id)
    where(room_id: room_id).last(500)
  end

end

app/models/notification.rb
class Notification < ApplicationRecord
  belongs_to :user, class_name: 'User', foreign_key: :to_user_id

  validates :content, presence: true, length: {maximum: 100}
  validates :post_id, :to_user_id, presence: true
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user, class_name: 'User', foreign_key: :user_id

  def user
    return User.find_by(id: self.user_id)
  end

  validates :title, {presence:true}
  validates :user_id, {presence:true}
  validates :game, {presence:true}
  validates :platform, {presence:true}
  validates :comment, {length:{maximum:300}}
end

app/models/request.rb
class Request < ApplicationRecord
  belongs_to :user, class_name: 'User', foreign_key: :user_id
  
  validates :post_id, presence: true
  validates :user_id, presence: true
  validates :post_user_id, presence: true
  validates :comment, length: {maximum: 300}

  def user
    return User.find_by(id: self.user_id)
  end
  def post
    return Post.find_by(id: self.post_id)
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  validates :name, presence: true
  has_many :posts, dependent: :destroy
  has_many :messages, dependent: :destroy
  has_many :requests, dependent: :destroy
  has_many :notifications, dependent: :destroy
  has_many :friends, dependent: :destroy

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  mount_uploader :image, ImageUploader
end

app/controllers/friends_controller.rb
class FriendsController < ApplicationController
  def index
    @friends = Friend.where(from_user_id: current_user.id)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def top
    @posts = Post.order(created_at: :desc).limit(20)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :sign_in_required ,only: [:new, :edit, :create, :update, :destroy]
  PER = 10

  def index
    @posts = Post.all.order(createde_at: :desc)
    @posts = Post.page(params[:page]).per(PER)
    set_prev_search_params
  end

  def new
    @post = Post.new
  end

  def show
    @post = Post.find_by(id:params[:id])
    if user_signed_in?
      @request = Request.find_by(post_id: @post.id, user_id: current_user.id)
    end
  end

  def create
    @post = Post.new(
      title: params[:title],
      user_id: current_user.id,
      game: params[:game],
      platform: params[:platform],
      comment: params[:comment]
    )
    if @post.save
      flash[:notice] = "投稿しました"
      redirect_to("/posts/index")
    else
      render("posts/new")
    end
  end

  def edit
    @post = Post.find_by(id:params[:id])
  end

  def update
    @post = Post.find_by(id:params[:id])
    if @post.user.id != current_user.id
      flash[:notice] = "許可されていません"
      redirect_to("/posts/index")
    end
    if @post.update(title: params[:title], game:params[:game], platform:params[:platform], comment:params[:comment])
      flash[:notice] = "編集しました"
      redirect_to("/posts/index")
    else
      render("posts/edit")
    end
  end

  def destroy
    @post = Post.find_by(id:params[:id])
    if @post.user.id != current_user.id
      flash[:notice] = "許可されていません"
      redirect_to("/posts/index")
    end
    @post.destroy
    flash[:notice] = "削除しました"
    redirect_to("/posts/index")
  end

  def set_prev_search_params
    prev_q = URI(request.referer).query
    prev_params = Rack::Utils.parse_nested_query(prev_q)
    params[:q] = prev_params['q']
  end

  def search
    unless params[:keyword].blank?
      @game = Post.where('game LIKE(?)', "%#{params[:keyword]}%")
      respond_to do |format|
        format.json { render '/', json: @game }
      end
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :sign_in_required, only: [:show]
  def show
    @user = User.find_by(id: params[:id])
    @room_id = message_room_id(current_user.id, @user.id)
    @posts = Post.where(user_id: @user.id)
  end
  def index
    @users = User.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/devise_helper.rb
module DeviseHelper
  def devise_error_messages!
    return "" if resource.errors.empty?

    html = ""
    messages = resource.errors.full_messages.each do |errmsg|
      html += <<-EOF
      <div class="alert alert-danger alert-dismissible" role="alert">
        <button type="button" class="close" data-dismiss="alert">
          <span aria-hidden="true">&times;</span>
          <span class="sr-only">close</span>
        </button>
        #{errmsg}
      </div>
      EOF
    end
    html.html_safe
  end

  def devise_error_messages?
    resource.errors.empty? ? false : true
  end

end

app/helpers/friends_helper.rb
module FriendsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/message_helper.rb
module MessageHelper

  def which_user? id
    return User.find_by(id: id)
  end
end

app/helpers/notification_helper.rb
module NotificationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/request_helper.rb
module RequestHelper
end

app/helpers/users_helper.rb
module UsersHelper

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>

  <%= csrf_meta_tags %>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  <title>EFriends</title>
</head>

<body class = "bg-light">
  <header>
    <nav class="navbar bg-secondary">
      <div class = "">
        <h1><%= link_to "E-friends", "/", class: "text-warning" %></h1>
      </div>
      <ul class = "navbar nav">
        <li class ="nav-item">
          <% if user_signed_in? %>
          <div class="dropdown">
            <button class="btn btn-default dropdown-toggle" type="button" id="dropdownMenu1" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              <img src="<%= current_user.image %>" width="50" class="mr-2">
              <span class="caret"></span>
            </button>
            <ul class="dropdown-menu" aria-labelledby="dropdownMenu1">
              <li><%= link_to "マイページ", "/users/#{current_user.id}/show", class: "text-dark" %></li>
              <li><%= link_to "受信リクエスト一覧", "/request/index", class: "text-dark" %></li>
              <li><%= link_to "フレンド", "/friends/#{current_user.id}", class: "text-dark"%></li>
              <li><%= link_to "ログアウト", sign_out_path, class: "text-dark" %></li>
            </ul>
          </div>
          <% else %>
          <%= link_to 'サインアップ', new_user_registration_path, class: "btn btn-outline-dark p-1 m-1" %>
          <%= link_to 'ログイン', new_user_session_path, class: "btn btn-outline-dark p-1 m-1" %>
          <% end %>
        </li>
        <li class ="nav-item"><%= link_to '新規投稿', '/posts/new', class: "btn btn-outline-dark p-1 m-1" %></li>
        <li class ="nav-item"><%= link_to '投稿一覧', '/posts/index', class: "btn btn-outline-dark p-1 m-1" %></li>
      </ul>
    </nav>
    <div class= "bg-secondary pb-2">
      <p class="mx-4 mb-1">掲示を検索する</p>
      <div class = "container text-left mx-4">
        <%= search_form_for @search, url: "/posts/index" do |f| %>
        <div class = "row">
          <div class= "col-xs-12 col-lg-3 pb-2">
            <%= f.text_field :title_cont ,placeholder: '掲示タイトル' ,id: "title"%>
          </div>
          <div class = "col-xs-12 col-lg-3 pb-2">
            <%= f.text_field :game_cont ,placeholder: 'ゲーム名' ,id:"game"%>
            <ul id = "result" class = "m-0">
            </ul>
          </div>
          <div class="col-xs-12 col-lg-3 pb-2">
            <%= f.text_field :platform_cont ,placeholder: 'プラットフォーム', id:"platform" %>
          </div>
          <div class ="col-xs-12 ml-3">
            <%= f.submit ("検索") , class: 'search-btn'%>
          </div>
        </div>
        <% end %>

      </div>
    </div>

  </header>

  <div class="alert-info text-center"><%= notice %></div>
  <div class="alert-danger text-center"><%= alert %></div>
  <div class ="alert-info text-center">
    <% if current_user.present? && Request.where(post_user_id: current_user.id).present? %>
    <%= link_to "リクエストが届いています", "/request/index" %>
    <% end %></div>
    <div class ="alert-info text-center">
      <% if @notifications.present? %>
      <% @notifications.each do |notification| %>
      <%= link_to notification.content, "/notification/#{notification.id}" %>
      <% end %>
      <% end %>
    </div>
    <div class = "mx-5 my-4 bg-white p-4">
      <%= yield %>
    </div>
  </body>
  </html>